import React from 'react';
import { motion } from 'framer-motion';
import { Lightbulb, Info, FileText, Briefcase, ChevronRight, Target } from 'lucide-react';
import { staggerContainer, fadeIn, scaleUp } from '../../utils/animations';

const CONTRACT_OPPS = [
  { id: 1, buyer: 'ITC Agri Business', crop: 'Organic Wheat', demand: '500 Quintals', price: '₹2,500/Qtl', duration: '6 Months', location: 'Maharashtra' },
  { id: 2, buyer: 'Reliance Fresh', crop: 'Tomatoes', demand: '200 Quintals', price: '₹1,200/Qtl', duration: '3 Months', location: 'Karnataka' },
  { id: 3, buyer: 'Patanjali Ayurved', crop: 'Aloe Vera', demand: '1000 Kg', price: '₹40/Kg', duration: 'Annual', location: 'Rajasthan' },
];

export const AdvisoryPortal = () => {
  return (
    <motion.div 
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="max-w-7xl mx-auto px-6 h-full"
    >
      <motion.div variants={fadeIn} className="mb-14 text-center">
        <h2 className="text-4xl font-extrabold text-white tracking-tight flex justify-center items-center gap-3 drop-shadow-xl">
          <Lightbulb className="w-10 h-10 text-amber-400 drop-shadow-[0_0_15px_rgba(251,191,36,0.8)]" />
          Advisory & Contracts
        </h2>
        <p className="mt-4 text-xl text-slate-300 max-w-2xl mx-auto font-medium">Daily farming intelligence generated by AI and local enterprise contracting opportunities.</p>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-10">
        
        {/* RAG Suggestions Box */}
        <motion.div variants={fadeIn} className="lg:col-span-1 space-y-8">
          
          <div className="glass-panel border-amber-500/30 rounded-3xl p-8 relative overflow-hidden shadow-[0_0_40px_rgba(245,158,11,0.1)]">
             <div className="absolute inset-0 bg-gradient-to-br from-amber-900/40 to-orange-900/10 z-[0]" />
             <div className="absolute -right-10 -top-10 opacity-20 z-[0] transform rotate-12 blur-sm">
               <Lightbulb className="w-56 h-56 text-amber-500" />
             </div>
             
             <h3 className="text-2xl font-black text-amber-300 mb-8 flex items-center gap-2 relative z-10 drop-shadow-md">
              <Target className="w-7 h-7 text-amber-400" /> Daily Smart Insight
             </h3>
             
             <div className="space-y-6 relative z-10">
                <div className="flex gap-4 text-white">
                  <Info className="w-7 h-7 shrink-0 text-amber-400 mt-0.5 drop-shadow-md" />
                  <p className="font-medium text-base text-slate-200 leading-relaxed tracking-wide">
                    Based on local humidity trends (85%), there is a severe warning for <strong className="text-amber-300">Leaf Rust</strong>. Preemptive spraying of Copper Oxychloride is highly recommended for Northern sectors before tomorrow's light rains.
                  </p>
                </div>
                <div className="flex gap-4 text-white">
                   <Target className="w-6 h-6 shrink-0 text-orange-400 mt-1 drop-shadow-md" />
                   <div className="text-slate-200">
                      <span className="block font-black text-orange-300 mb-1 tracking-wide">Market Tip:</span>
                      Organic Rice premiums have jumped by 15% due to export demands. Ensure organic certification is up to date ahead of the harvest.
                   </div>
                </div>
             </div>
          </div>

          <div className="glass-card rounded-3xl p-8 flex flex-col items-center justify-center text-center border-t border-emerald-500/30">
             <div className="p-5 bg-emerald-900/40 rounded-full mb-6 border border-emerald-500/50 shadow-[0_0_20px_rgba(16,185,129,0.3)]">
               <FileText className="w-10 h-10 text-emerald-400" />
             </div>
             <h4 className="font-extrabold text-white text-xl drop-shadow-md">Crop Insurance Portal</h4>
             <p className="font-medium text-slate-400 mt-3 mb-8 tracking-wide">File claims directly or renew your Pradhan Mantri Fasal Bima Yojana (PMFBY) premium effortlessly.</p>
             <button className="w-full py-4 bg-emerald-500/20 text-emerald-300 font-black tracking-widest uppercase rounded-2xl hover:bg-emerald-500/40 border border-emerald-500/50 transition-all hover:shadow-[0_0_20px_rgba(16,185,129,0.4)]">Access Portal</button>
          </div>

        </motion.div>

        {/* Contract Farming Opportunities */}
        <motion.div variants={fadeIn} className="lg:col-span-2 glass-panel rounded-3xl p-8 border-indigo-500/20">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-10 gap-4">
            <h3 className="text-3xl font-black text-white flex items-center gap-3 drop-shadow-md">
              <Briefcase className="w-8 h-8 text-indigo-400 drop-shadow-[0_0_10px_rgba(129,140,248,0.8)]" /> Contract Board
            </h3>
            <span className="text-sm font-bold tracking-widest uppercase text-indigo-300 bg-indigo-900/40 border border-indigo-500/40 px-4 py-2 rounded-full shadow-[0_0_15px_rgba(99,102,241,0.2)]">
              3 Active Requests
            </span>
          </div>
          
          <div className="space-y-5">
            {CONTRACT_OPPS.map((contract) => (
              <motion.div 
                key={contract.id}
                variants={scaleUp}
                className="group flex flex-col xl:flex-row xl:items-center justify-between p-6 glass-card rounded-2xl border-white/5 hover:border-indigo-500/40 transition-all duration-500"
              >
                <div className="mb-6 xl:mb-0">
                  <h4 className="font-black text-white text-xl mb-3 drop-shadow-md">
                    {contract.crop} for <span className="text-indigo-300">{contract.buyer}</span>
                  </h4>
                  <div className="flex flex-wrap items-center gap-x-4 gap-y-3 text-sm text-slate-300 font-bold tracking-wide">
                     <span className="bg-slate-900/60 shadow-inner px-3 py-1.5 rounded-lg border border-white/10">Demand: {contract.demand}</span>
                     <span className="bg-emerald-900/30 text-emerald-400 shadow-inner px-3 py-1.5 rounded-lg border border-emerald-500/30">Rate: {contract.price}</span>
                     <span className="bg-slate-900/60 shadow-inner px-3 py-1.5 rounded-lg border border-white/10">{contract.duration}</span>
                  </div>
                </div>
                <button className="self-start xl:self-center flex items-center gap-2 bg-indigo-600/30 text-indigo-300 border border-indigo-500/50 hover:bg-indigo-500 hover:text-white px-6 py-3 rounded-xl font-black uppercase tracking-wider transition-all shadow-lg group-hover:shadow-[0_0_20px_rgba(99,102,241,0.5)] whitespace-nowrap">
                  Apply Now <ChevronRight className="w-5 h-5" />
                </button>
              </motion.div>
            ))}
          </div>
          
          <div className="mt-10 text-center">
             <button className="text-slate-400 font-bold uppercase tracking-widest text-sm hover:text-white transition-colors border-b border-transparent hover:border-white pb-1">
               Load More Opportunities...
             </button>
          </div>

        </motion.div>

      </div>
    </motion.div>
  );
};
